http:
  port: 7778
  adminPort: 7779
  rootPath: /app/*
  requestLog:
    console:
      enabled: true
    file:
      enabled: false

youtubeKey: AIzaSyDLnw29DUCETqv9gL2YtCx6iLNkEmt1ArE
heartBeat: 8640000000000
